<?php

namespace App\Model\user;

use App\Model\admin\city;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Spatie\Activitylog\Traits\LogsActivity;

class tasktechnician extends Model
{

    use LogsActivity;

    protected $fillable = ['district', 'task', 'technician_id', 'city_id', 'user_id', 'slug', 'status'];
    protected static $logAttributes = [ 'district','task','technician_id','city_id','user_id','slug','status'];

    //public function member()
    //{
    //    return $this->belongsTo(User::class);
    //}

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            if (auth()->check()){
                $model->member_id = auth()->id();
            }
            $model->ip = request()->ip();
        });
        static::updating(function($model){
            if (auth()->check()){
                $model->member_id = auth()->id();
            }
            $model->ip = request()->ip();
        });
    }

    public function isOnline()
    {
        return Cache::has('user-is-online-' . $this->id);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function city()
    {
        return $this->belongsTo(city::class);
    }

    public function technician()
    {
        return $this->belongsTo(technician::class);
    }

    use Sluggable;
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => '',
            ]

        ];
    }
}
