<?php

namespace App\Model\user;

use App\Model\admin\city;
use App\Model\admin\occupation;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Spatie\Activitylog\Traits\LogsActivity;

class technician extends Model
{
    use LogsActivity;

    protected $fillable = [
        'district',
        'member_id',
        'city_id',
        'user_id',
        'slug',
        'occupation_id',
        'status'
    ];
    protected static $logAttributes = [ 'district','member_id','city_id','user_id','occupation_id','status'];


    public function member()
    {
        return $this->belongsTo(User::class,'member_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            if (auth()->check()){
                $model->member_id = auth()->id();
            }
            $model->ip = request()->ip();
        });
        static::updating(function($model){
            if (auth()->check()){
                $model->member_id = auth()->id();
            }
            $model->ip = request()->ip();
        });
    }


    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function city()
    {
        return $this->belongsTo(city::class);
    }

    public function occupation()
    {
        return $this->belongsTo(occupation::class);
    }


    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function isOnline()
    {
        return Cache::has('user-is-online-' . $this->id);
    }

    use Sluggable;
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => str_slug(date('YmdHis') . str_random(30)),
            ]

        ];
    }

    public function tasktechnicians()
    {
        return $this->hasMany(tasktechnician::class,'technician_id');
    }
}
