<?php

namespace App\Model\user;

use App\Mail\NewUserWelcomeMail;
use App\Model\admin\country;
use App\Model\admin\task;
use App\Notifications\RegisteredUsers;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Cache;
use Laravel\Passport\HasApiTokens;
use Overtrue\LaravelFollow\Traits\CanBeFollowed;
use Overtrue\LaravelFollow\Traits\CanFollow;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable,HasApiTokens,HasRoles,CanFollow, CanBeFollowed;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guard_name = 'web';
    protected $fillable = [
        'name',
        'first_name',
        'last_name',
        'work',
        'sex',
        'age',
        'email',
        'body',
        'username',
        'color_name',
        'color_style',
        'phone',
        'cap',
        'avatar',
        'avatarcover',
        'password',
        'address',
        'country_id'
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($user) {
            $user->ip = request()->ip();

            $user->technician()->create([
                'title' => $user->username,
            ]);
            //Mail::to($user->email)->send(new NewUserWelcomeMail());
        });
    }

    /**
     * Send the email verification notification.
     *
     * @return void
     */
    public function sendEmailVerificationNotification()
    {
        $this->notify(new RegisteredUsers());
    }

    public function visits()
    {
        return visits($this);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function isOnline()
    {
        return Cache::has('user-is-online-' . $this->id);
    }


    public function my_country()
    {
        return $this->belongsTo(country::class,'country_id');
    }

    public function getRouteKeyName()
    {
        return 'username';
    }


    public function tasks()
    {
        return $this->hasMany(task::class,'administrator_id');
    }

    public function technician()
    {
        return $this->hasOne(technician::class);
    }
}
